# -*- coding: utf-8 -*-
"""EqualFooting_PlotReproduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCqFw6qzmg_qNuAKy8W8-kvjuzC2paFZ
"""

from scipy.special import iv, kv, ive, kve, gammaln, gamma, legendre
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

rho_0 = 4
epsilon = 0.05 # Strength of diffusive degradation
arg_0 = 2 * epsilon * np.sqrt(rho_0)
arg_e = 2 * epsilon
alpha = 1 # Strength of secretion
beta = 1 # Strength of degradation at surface
B0 = 1 # Number of ligand receptors at cell surface
pole_tolerance = 1
lim_tol = 1e-05
zero_tol = 1e-300 # For comparing numbers with 0, because these Bessels get ridiculously tiny with small epsilon
# How did Claude know to use 300? Answer: It was essentially arbitrary

def set_epsilon(val):
  global epsilon, arg_0, arg_e
  epsilon = val
  arg_0 = 2 * epsilon * np.sqrt(rho_0)
  arg_e = 2 * epsilon

def set_rho_0(val):
  global rho_0, arg_0
  rho_0 = val
  arg_0 = 2 * epsilon * np.sqrt(rho_0)

def set_beta(val):
  global beta
  beta = val

def set_B0(val):
  global B0
  B0 = val

def set_lim_tol(val):
  global lim_tol
  lim_tol = val

# Update 5/14/26: Tried these small-arg expansions when epsilon gets small, they don't seem to work effectively;
# probably because they keep canceling each other out in the denominator.

# Edit: Nevermind, when sticking with the regular iv and kv fncs for small args, zero terms are still appearing left and right
# in the denominator of X_l, but none of the Chi values are negative anymore. Not sure why this is happening
# but I think I'll stick with the regular fncs from now on.

# So ok. I'm sticking with the regular fncs. Why are all these 0s still appearing in the denominator of X_l?
# Question 1: Does it matter? Even for normal-sized epsilon, these zeros are still appearing, and the graph
# looked fine. Examining the graph more closely - I'll test for theta behind the cell next and see if the Chis become negative.
# Also, for what it's worth, the iv / kv ratio never seems to be close to zero, which means the denominator
# as a whole is evaluating to close to zero, which is unfortunate cause it makes it a lot harder to debug :(

# Alright, Chi(3, 135) is sus af with the oscillation btwn iterations but actually all these Chis are evaluating
# to positive values which is really good! What to try next?

# Next, ignoring the zero in denom problem for a second, I want to confirm that a higher epsilon leads to
# a lower peak Chi value (or doesn't affect the peak, rather than increase it)
# This is confirmed!

# Ok, so the zero in denominator in X_l is still weird, and I'll definitely come back to it should the need
# arise, but for now by setting the iterations to 50, as demonstrated by my debug plots, the heatmaps converge
# without a problem! Well, sort of; the far field solution is everywhere 0 ( ಠ ͜ʖಠ)

# Oh yeah, also, epsilon still cannot be exactly 0 or else X_l just goes straight to NaN. How to fix...

# Update: The log approximation for the ratio was also breaking the far field solutions. Gemini is apparently pretty useless when it comes to this stuff.

# Now that I've returned everything back to just standard functions, and simply reduced the iterations, the heatmaps are more or less working.
# Here are some observations:
# - The effects of beta almost completely disappear when epsilon is 1, although they are still visible if scrutinizing closely.
# - For eventual publication, might have to figure out how to get rid of that ring artifact at the boundary between the near and far field solutions? Maybe
#   use the averages idea I was talking about? For now though, not a problem.
# - Increasing epsilon leads to a sharper decay in concentration close to the source, and additionally reduces the amplitude of concentration at all points.
# - This one might be an issue: Increasing epsilon leads to concentration values going below 0, which shouldn't really be legal.

# LEAVE-OFF POINT 5/14/26. TODO: Check debug Chi convergence graphs for epsilon = 1 to see if there are any negative values, or if those negatives are just a
# result of the artifacts. If the negative values do exist, this either means epsilon cannot go above a certain max range or the code is broken.
# Think about which one is more likely later.

# 5/15 Start

# Ok, update: The reason why there is a ring artifact in the heatmap at rho = rho_0 is because the series does not converge there, but oscillates
# back and forth probably at a frequency determined by the angle. So, after a certain number of iterations, when it is stopped, it will be
# at a random point in its oscillation - except those artifacts aren't random, are they. So probably a predictable point in its oscillation
# which leads to the artifact. Again, probably don't need to worry about this now but just an observation.

# Also, this is now confirmed why the epsilon < 0 issue is happening: sometimes, when the oscillation is stopped, its value will happen to
# be below 0 at that point. Now that I've confirmed this, I think it's still best to circle back to this issue as it does not impact the anisostropy,
# which is the focus for the next tasks.

def log_iv_over_kv(nu, x):
    """log( iv(nu,x) / kv(nu,x) ) computed stably for any x >= 0."""
    if np.isclose(epsilon, 0., atol=zero_tol):
        # small-argument asymptotics in log-space
        # log iv(nu,x) ~ nu*log(x/2) - gammaln(nu+1)
        # log kv(nu,x) ~ gammaln(nu) - nu*log(x/2) - log(2)   (nu > 0)
      log_iv = nu * np.log(x / 2) - gammaln(nu + 1)
      log_kv = gammaln(nu) - nu * np.log(x / 2) - np.log(2)
      return log_iv - log_kv
    # general: use scaled functions, ratio of ive/kve times exp(-2x)
    # ive = iv*exp(-x), kve = kv*exp(x)  =>  iv/kv = (ive/kve)*exp(-2x)
    log_ratio = np.log(ive(nu, x)) - np.log(kve(nu, x)) + 2 * x
    return log_ratio

def iv_over_kv(nu, x):
    return np.exp(log_iv_over_kv(nu, x))

def iv_kv_sum(nu, x):
    ive_sum = ive(nu - 1, x) + ive(nu + 1, x)
    kve_sum = kve(nu - 1, x) + kve(nu + 1, x)
    return ive_sum, kve_sum

# ── X_l ──────────────────────────────────────────────────────────────────────

def X_l(l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return X_l_limit(l)

    order = 2 * l + 1
    arg   = arg_0

    log_r    = log_iv_over_kv(order, arg)
    ratio    = np.exp(log_r) # keep for diagnostics

    ive_sum, kve_sum = iv_kv_sum(order, arg)
    inner = np.exp(log_r) * kve_sum + np.exp(2 * arg) * ive_sum

    # if np.isclose(inner, 0.0, atol=zero_tol):
    #     if np.isclose(ratio, 0, atol=zero_tol):
    #         print(f"Zero denominator and zero iv/kv in X_l at l={l}")
    #     else:
    #         print(f"Zero denominator in X_l at l={l}")
    # elif np.isclose(ratio, 0, atol=zero_tol):
    #     print(f"Zero iv/kv in X_l at l={l}")

    # X_l = 2*order*alpha / (sqrt(epsilon)*rho_0) / denom
    #      = 2*order*alpha / (sqrt(epsilon)*rho_0) * exp(arg) / inner
    prefactor = 2 * order * alpha / (epsilon * rho_0)
    return prefactor * np.exp(arg) / inner


# ── Y_l ──────────────────────────────────────────────────────────────────────

def Y_l(l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return Y_l_limit(l)

    order = 2 * l + 1
    arg   = arg_e

    ive_sum_e, kve_sum_e = iv_kv_sum(order, arg)
    two_beta_1 = 2 * beta + 1
    # sq_eps     = np.sqrt(epsilon)

    numer_scaled = two_beta_1 * ive(order, arg) - epsilon * ive_sum_e
    denom_scaled = two_beta_1 * kve(order, arg) + epsilon * kve_sum_e

    if np.isclose(denom_scaled, 0.0, atol=zero_tol):
        raise Exception("Zero denominator in Y_l (scaled)")

    ratio_nd = numer_scaled / denom_scaled

    return -X_l(l) * ratio_nd * np.exp(2 * arg)


# ── Z_l ──────────────────────────────────────────────────────────────────────

def Z_l(l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return Z_l_limit(l)

    order = 2 * l + 1
    log_r0 = log_iv_over_kv(order, arg_0)
    return X_l(l) * np.exp(log_r0) + Y_l(l)


# ── radial functions ──────────────────────────────────────────────────────────

def R_l_lt(rho, l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return R_l_lt_limit(rho, l)
    order = 2 * l + 1
    arg   = 2 * epsilon * np.sqrt(rho)
    return (X_l(l) * ive(order, arg) * np.exp(arg)
            + Y_l(l) * kve(order, arg) * np.exp(-arg)) / np.sqrt(rho)


def R_l_gt(rho, l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return R_l_gt_limit(rho, l)
    order = 2 * l + 1
    arg   = 2 * epsilon * np.sqrt(rho)
    return Z_l(l) * kve(order, arg) * np.exp(-arg) / np.sqrt(rho)


# ── limiting cases ──────────────────────────────────────────────────────────

def X_l_limit (l):
  return alpha / rho_0 ** (l + 1)

def Y_l_limit (l):
  return X_l_limit(l) * (l - beta) / (l + beta + 1)

def Z_l_limit (l):
  return X_l_limit(l) * rho_0 ** (2*l + 1) + Y_l_limit(l)

def R_l_lt_limit (rho, l):
  return X_l_limit(l) * rho ** l + Y_l_limit(l) / rho ** (l + 1)

def R_l_gt_limit (rho, l):
  return Z_l_limit(l) / rho ** (l + 1)

def is_near_pole (rho, theta):
  if np.abs(rho) < pole_tolerance: return True
  x = rho * np.sin(theta)
  z = rho * np.cos(theta)
  if np.sqrt(x**2 + (z-rho_0)**2) < pole_tolerance: return True
  return False

def R_l (rho, theta, l):
  if is_near_pole(rho, theta):
    return np.nan
  val = R_l_lt(rho, l) if rho <= rho_0 else R_l_gt(rho, l)
  return val

vR_l = np.vectorize(R_l)

# LEAVE-OFF POINT LUNCH 6/11/26: Did I fuck up the derivations? Might need to go back and double check.
# Just remember: Sqrt of the old epsilon is the new epsilon, and the old epsilon = the new epsilon^2.

def Chi (rho, theta, n=25, debug=False):
  sol = 0
  for l in range(n):
    P_l = legendre(l)
    sol += vR_l(rho, theta, l) * P_l(np.cos(theta))
  # print(sol)
  # if debug and sol < 0: sol = 0
  # if sol < 0: print(f"Warning: $\\chi$({rho},{theta}) = {sol} < 0 after {n} iterations")
  return sol

set_rho_0(4)
# Problem: Lefebre says G - F > 0 when rho_0 > 2, but mine only satisfies
# the same inequality when rho_0 > 2.5

F = ( rho_0 ** 2 * (rho_0 - 1) ) / (rho_0*(rho_0-1) - 1) - np.log(rho_0) / 2 + np.log( (rho_0*(rho_0-1) - 1) / (rho_0*(rho_0-1)) ) / 2

G = ( (rho_0+1)*(rho_0**2 + rho_0 - 1) + rho_0) / (rho_0*2 + rho_0 + 1) - np.log(rho_0+1) / 2 + np.log( (rho_0**2 + rho_0 - 1) / (rho_0*(rho_0+1)) ) / 2

def set_alpha(val):
  global alpha, F, G
  alpha = val

  F = ( rho_0 ** 2 * (rho_0 - 1) ) / (rho_0*(rho_0-1) - 1) - np.log(rho_0) / 2 + np.log( (rho_0*(rho_0-1) - 1) / (rho_0*(rho_0-1)) ) / 2
  G = ( (rho_0+1)*(rho_0**2 + rho_0 - 1) + rho_0) / (rho_0*2 + rho_0 + 1) - np.log(rho_0+1) / 2 + np.log( (rho_0**2 + rho_0 - 1) / (rho_0*(rho_0+1)) ) / 2

def Anisotropy ():
  return R_l_lt(1, 1) / (R_l_lt(1, 0) * 3)

def Anisotropy_Lefebre() :
  numer = 2 + epsilon*(G-F)*(rho_0**2 - 1)
  denom = 3*( 2*rho_0 - epsilon*(F+G)*(rho_0**2 - 1) )
  return numer / denom

kappa = 1

def set_kappa(val):
  global kappa
  kappa = val

def Chi_front (n=25):
  sum = 0
  for l in range(1, n, 1):
    sum += ( 1 / (2*l+1) ) * R_l_lt(1, l) * (legendre(l+1)(0)-legendre(l-1)(0)) # This method of calling Legendres works
  return 2*np.pi*( R_l_lt(1, 0) - sum )

def Chi_back (n=25):
  sum = 0
  for l in range(1, n, 1):
    sum += ( 1 / (2*l+1) ) * R_l_lt(1, l) * (legendre(l+1)(0)-legendre(l-1)(0))
  return 2*np.pi*( R_l_lt(1, 0) + sum )

def g_abs ():
  return 4*np.pi*R_l_lt(1, 0)

def g_rel (n=25):
  return (Chi_front(n) - Chi_back(n)) / Chi_back(n)

def output (n=25):
  return Chi_front(n) / (Chi_front(n)+kappa) - Chi_back(n) / (Chi_back(n)+kappa)

def bound_complex (theta, n=25):
  return B0 * Chi(1, theta, n) / ( Chi(1, theta, n) + kappa)

def bound_SNR (n=25):
  theta_vals = np.arange(0, np.pi, np.deg2rad(1))
  dth = theta_vals[1] - theta_vals[0]

  b_vals = np.array([bound_complex(theta, n) for theta in theta_vals])
  jacobian = np.sin(theta_vals)

  numer = np.sum(b_vals * np.cos(theta_vals) * jacobian) * dth * 2 * np.pi
  denom = np.sum(b_vals * jacobian) * dth * 2 * np.pi
  denom = np.sqrt(denom)

  return numer / denom

def SNR (use_avg, n=25):
  if use_avg:
    return ( Chi_front(n) - Chi_back(n) ) / np.sqrt( Chi_front(n) + Chi_back(n) )
  else:
    chi_f = Chi(1, 0, n)
    chi_b = Chi(1, np.pi, n)
    return ( chi_f - chi_b ) / np.sqrt( chi_f + chi_b )

def fake_SNR (n=25):
  chi_f = Chi(1, 0, n)
  chi_b = Chi(1, np.pi, n)
  return ( chi_f - chi_b ) / (chi_f + chi_b)

def new_SNR ():
  return R_l_lt(1, 1) / np.sqrt(R_l_lt(1, 0))

def new_new_SNR ():
  return ( X_l(1) * ive(3, arg_e) * np.exp(arg_e) + Y_l(1) * kve(3, arg_e) * np.exp(-arg_e) ) \
    / np.sqrt ( X_l(0) * ive(1, arg_e) * np.exp(arg_e) + Y_l(0) * kve(1, arg_e) * np.exp(-arg_e) )

def reset():
  set_beta(0)
  set_epsilon(0)
  set_kappa(1)
  set_B0(1)

# Because of the nature of the X_l term, for small epsilon stuff keeps breaking after many iterations. The purpose of this cell is
# to figure out exactly what is breaking so I can fix it.

def test_Chi(theta, n=25):
  print("Theta = ", theta, ", num iters = ", n)
  for rho in range(5):
    print(f"Chi({rho}, {theta}, {n}): ", Chi(rho, theta, n))
  print("\n")

angle_colors = {
    -180: "brown",
    -135: "red",
    -90: "orange",
    -45: "yellow",
    0: "green",
    45: "blue",
    90: "purple",
    135: "pink",
}

radius_colors = {
    1: "brown",
    2: "red",
    3: "orange",
    4: "gold",
    5: "yellow",
}

def plot_convergence(rho, theta, max_iters):
  n = np.arange(0, max_iters+1, 1, dtype=int)
  Chi_vals = np.array([])
  for l in range(max_iters+1):
    Chi_vals = np.append(Chi_vals, Chi(rho, theta, l))
  if Chi_vals[-1] < 0.0:
    print(f"Warning: $\\chi$({rho},{theta}) = {Chi_vals[-1]} < 0 after {l} iterations")
  # else:
    # print(f"$\\chi$({rho},{theta}) converged to f{Chi_vals[-1]} after {l} iterations")
  plt.plot(n, Chi_vals, label=f"$\\chi$({rho},{theta})", color=radius_colors[rho])

epsilon_colors = {
    # 0.00001: "pink",
    # 0.0001: "black",
    0.001: "brown",
    0.01: "red",
    0.1: "orange",
    1: "gold",
    10: "yellow",
    100: "green",
    # 1000: "blue"
}

def plot_convergence_front_back(max_iters, front):
  if front:
    Chi_fnc = Chi_front
  else:
    Chi_fnc = Chi_back
  n = np.arange(0, max_iters+1, 1, dtype=int)
  Chi_vals = np.array([])
  for l in range(max_iters+1):
    Chi_vals = np.append(Chi_vals, Chi_fnc(l))
    if Chi_vals[-1] == np.nan:
      print(f"Warning: $\\chi_{{F}}$ = {Chi_vals[-1]} after {l} iterations")
      continue
  if Chi_vals[-1] < 0.0:
    print(f"Warning: $\\chi_{{F}}$ = {Chi_vals[-1]} < 0 after {l} iterations")
  # else:
    # print(f"$\\chi$({rho},{theta}) converged to f{Chi_vals[-1]} after {l} iterations")
  label = "F" if front else "B"
  plt.plot(n, Chi_vals, label=f"$\\chi_{label}$ at $\\varepsilon={epsilon}$", color=epsilon_colors[epsilon])

def compare_convergences_front_back(iters):
  for eps_val, color in epsilon_colors.items():
    set_epsilon(eps_val)
    plot_convergence_front_back(iters, True)
    plot_convergence_front_back(iters, False)

  plt.gcf().set_size_inches(10, 10)
  plt.plot(np.arange(0, iters+1, 1), np.zeros(iters+1), color="green", linestyle="--")
  plt.legend()
  plt.show()

def compare_convergences(eps_val, rho_min, rho_max, theta_min, theta_max, iters):
  set_epsilon(eps_val)
  for theta in range(theta_min, theta_max+1, 45):
    for rho in range(rho_min, rho_max+1):
      if rho is not 4: continue
      if is_near_pole(rho, theta): continue
      plot_convergence(rho, theta, iters)

  # plt.legend()
  plt.gcf().set_size_inches(10, 10)
  plt.plot(np.arange(0, iters+1, 1), np.zeros(iters+1), color="green", linestyle="--")
  plt.legend()
  plt.show()

def plot_chi_heatmap (x_bounds, z_bounds, cell_size, ax, iters=25, chi_debug=False):
  x, z = np.meshgrid(np.arange(x_bounds[0], x_bounds[1], cell_size), np.arange(z_bounds[0], z_bounds[1], cell_size))
  # doing normal np.atan(x / z) produces incorrect plot due to not picking the quadrants correctly
  chi = Chi(np.sqrt(z ** 2 + x ** 2), np.atan2(x, z), iters, chi_debug)
  img = ax.imshow(chi, extent=[x_bounds[0],x_bounds[1],z_bounds[0],z_bounds[1]], cmap="YlOrBr", origin='lower')
  ax.set_xlabel("x", fontsize="x-large")
  ax.set_ylabel("z", fontsize="x-large")
  ax.set_xticks([x_bounds[0], 0, x_bounds[1]])
  ax.set_yticks([z_bounds[0], 0, z_bounds[1]])
  ax.tick_params(labelsize="x-large")
  ax.set_title("$\\chi(\\lambda,\\theta)$", pad=10)
  return img

# Important: only works for cell sizes with one sig fig
# Also a lot slower, only use this version if you really need it
def plot_chi_heatmap_debug (x_bounds, z_bounds, num_cells_per_side, ax, iters=25, chi_debug=False):
  x_vals, z_vals = np.meshgrid( np.arange(x_bounds[0], x_bounds[1], (x_bounds[1] - x_bounds[0]) / num_cells_per_side),
                                np.arange(z_bounds[0], z_bounds[1], (z_bounds[1] - z_bounds[0]) / num_cells_per_side) )
  chis = []

  for z in z_vals[:, 0]:
    row = np.array([])
    for x in x_vals[0]:
      rho = np.sqrt( z**2 + x**2 )
      theta = np.atan2(x, z)
      chi = Chi(rho, theta, iters,  chi_debug)
      if chi < 0.0:
        print(f"Warning: $\\chi({rho}, {theta}) = {chi} < 0 after {iters} iterations)")
        chi = 0.0
      row = np.append(row, chi)
    chis.append(row)
    print(f"All chi values at z={z} found")

  img = ax.imshow(np.asarray(chis), extent=[x_bounds[0],x_bounds[1],z_bounds[0],z_bounds[1]], cmap="YlOrBr", origin='lower')
  ax.set_xlabel("x", fontsize="x-large")
  ax.set_ylabel("z", fontsize="x-large")
  ax.set_xticks([x_bounds[0], 0, x_bounds[1]])
  ax.set_yticks([z_bounds[0], 0, z_bounds[1]])
  ax.tick_params(labelsize="x-large")
  ax.set_title(f"$\\beta={beta}$, $\\varepsilon={epsilon}$", pad=10)
  return img

GREEK_LETTERS = {
    "alpha":   ("α", "Α"),
    "beta":    ("β", "Β"),
    "gamma":   ("γ", "Γ"),
    "delta":   ("δ", "Δ"),
    "epsilon": ("ε", "Ε"),
    "zeta":    ("ζ", "Ζ"),
    "eta":     ("η", "Η"),
    "theta":   ("θ", "Θ"),
    "iota":    ("ι", "Ι"),
    "kappa":   ("κ", "Κ"),
    "lambda":  ("λ", "Λ"),
    "mu":      ("μ", "Μ"),
    "nu":      ("ν", "Ν"),
    "xi":      ("ξ", "Ξ"),
    "omicron": ("ο", "Ο"),
    "pi":      ("π", "Π"),
    "rho":     ("ρ", "Ρ"),
    "sigma":   ("σ", "Σ"),
    "tau":     ("τ", "Τ"),
    "upsilon": ("υ", "Υ"),
    "phi":     ("φ", "Φ"),
    "chi":     ("χ", "Χ"),
    "psi":     ("ψ", "Ψ"),
    "omega":   ("ω", "Ω"),
}


def greek(s: str) -> str:
    """Convert a romanized Greek letter name to its Unicode symbol.

    Capitalization rules:
        - ALL CAPS  (e.g. "ALPHA") → uppercase Greek letter (Α)
        - Title case (e.g. "Alpha") → uppercase Greek letter (Α)
        - Anything else (e.g. "alpha") → lowercase Greek letter (α)

    Returns None if the string is not a recognized Greek letter name.
    """
    key = s.strip().lower()
    if key not in GREEK_LETTERS:
        return key

    lower, upper = GREEK_LETTERS[key]
    if s.isupper() or (s[0].isupper() and s[1:].islower()):
        return upper
    return lower

def plot_metric_heatmap (metric_name="output", metric_fnc=output, beta_max=5, eps_max=5, num_cells_per_side=25, ax=None, show_max=False, **kwargs):
  beta_vals, eps_vals = np.meshgrid(np.arange(0, beta_max, beta_max / num_cells_per_side), np.arange(0, eps_max, eps_max / num_cells_per_side))
  vals = []
  max_val = 0
  max_beta = 0
  max_eps = 0
  for eps_val in eps_vals[:, 0]:
    row = np.array([])
    for beta_val in beta_vals[0]:
      set_epsilon(eps_val)
      set_beta(beta_val)
      val = metric_fnc(**kwargs)
      # print(val)
      if val > max_val:
        max_beta = beta_val
        max_eps = eps_val
        max_val = val
      row = np.append(row, val)
    vals.append(row)
    print(f"So far: Max {metric_name} = {max_val}, reached at epsilon = {max_eps}, beta = {max_beta}")


  print(f"Final: Max {metric_name} = {max_val}, reached at epsilon = {max_eps}, beta = {max_beta}")
  img = ax.imshow(np.asarray(vals), extent=[0, beta_max, 0, eps_max], cmap="YlOrBr", origin='lower')
  if show_max:
    ax.plot(max_beta, max_eps, 'x')
  ax.set_xlabel("$\\beta$", fontsize="x-large")
  # label = "$\\sqrt{{\\varepsilon}}$" if sqrt_eps else "$\\varepsilon$"
  ax.set_ylabel("$\\varepsilon$", fontsize="x-large")
  ax.set_xticks([0, beta_max])
  ax.set_yticks([0, eps_max])
  ax.tick_params(labelsize="x-large")
  ax.set_title(metric_name, pad=10)
  ax.set_aspect(max(beta_max, eps_max) / min(beta_max, eps_max))
  return img

def max_metric_val(metric_fnc=output, beta_max=5, eps_max=5, num_cells_per_side=25, **kwargs):
  beta_vals, eps_vals = np.meshgrid(np.arange(0, beta_max, beta_max / num_cells_per_side), np.arange(0, eps_max, eps_max / num_cells_per_side))
  vals = []
  max_val = 0
  max_beta = 0
  max_eps = 0
  for eps_val in eps_vals[:, 0]:
    row = np.array([])
    print("boom")
    for beta_val in beta_vals[0]:
      set_epsilon(eps_val)
      set_beta(beta_val)
      val = metric_fnc(**kwargs)
      print(val)
      if val > max_val:
        max_beta = beta_val
        max_eps = eps_val
        max_val = val
      row = np.append(row, val)
    vals.append(row)

  print(f"Max value = ({max_val}), reached at epsilon = {max_eps}, beta = {max_beta}")
  return max_eps, max_beta, max_val

gammas = np.linspace(0, 1, 20)

B_colors = {
    0.0001: "pink",
    0.001: "black",
    0.01: "brown",
    0.1: "red",
    1.0: "orange",
    10.0: "gold",
    100.0: "yellow",
    1000.0: "green",
    10000.0: "blue",
    100000.0: "purple"
}

def plot_budget_curves(metric_name="output", metric_fnc=output, Bmin=0.01, Bmax=100, ax=None):
  B = Bmin
  while B <= Bmax:
    vals = np.array([])
    for gamma in gammas:
      set_beta(B*(1 - gamma))
      set_epsilon(B*gamma)
      vals = np.append(vals, metric_fnc())

    maximizer_index = np.argmax(vals)
    print(f"Max {metric_name} = ({vals[maximizer_index]}), reached at gamma = {gammas[maximizer_index]}")
    ax.plot(gammas, vals, color=B_colors[B], label=f"B={B}")
    B *= 10

  ax.set_xlabel("$\\gamma$", fontsize="x-large")
  ax.set_ylabel(metric_name, fontsize="x-large")
  ax.set_xticks([0, 1])
  ax.tick_params(labelsize="x-large")
  # ax.set_xlim(0.9, 1)
  # ax.set_title("Production Possibilities Frontier: $\\beta$ & $\\epsilon$", fontsize="xx-large", pad=10)
  ax.legend()

def plot_for_multiple_kappas(kappa_vals, plot_fnc, figsize=(14, 5), by_row=False, num_cols = None, **kwargs):
  if by_row:
    fig, axes = plt.subplots(len(kappa_vals), num_cols, figsize=figsize, sharey='row')
  else:
    fig, axes = plt.subplots(1, len(kappa_vals), figsize=figsize)
  for i in range(len(kappa_vals)):
    set_kappa(kappa_vals[i])
    print(kappa)
    ax = axes if len(kappa_vals) == 1 else axes[i]
    print(ax)
    img = plot_fnc(ax=ax, **kwargs)
    ax.set_title(f"$\\kappa={kappa}$")
    if plot_fnc == plot_metric_heatmap: fig.colorbar(img, ax=ax, fraction=0.1)

def max_val_for_multiple_kappas(kappa_min, kappa_max, metric_fnc=bound_SNR, **kwargs):
  kappa_vals = np.logspace(kappa_min, kappa_max, 40)

  data = []
  max_eps_vals = []
  max_beta_vals = []
  for val in kappa_vals:
    set_kappa(val)
    print(f"Kappa = {val}")
    max_eps, max_beta, max_val= max_metric_val(metric_fnc, num_cells_per_side=10, **kwargs)
    max_eps_vals.append(max_eps)
    max_beta_vals.append(max_beta)
    data.append(max_val)

  plt.rcParams.update({'font.size': 22})
  sc = plt.scatter(max_beta_vals, max_eps_vals, c=kappa_vals, cmap="YlOrBr", norm="log")
  plt.xlabel("$\\beta$")
  plt.ylabel("$\\varepsilon$")
  plt.gcf().colorbar(sc)

# max_val_for_multiple_kappas(-3, 1)

def plot_output_heatmap (vs_beta, param_bounds, kappa_bounds, num_cells_per_side=25, ax=None, iters=25):
  param_vals, kappa_vals = np.meshgrid(
      np.arange(param_bounds[0], param_bounds[1] + np.abs(param_bounds[1] - param_bounds[0]) / num_cells_per_side, np.abs(param_bounds[1] - param_bounds[0]) / num_cells_per_side),
      np.arange(kappa_bounds[0], kappa_bounds[1] + np.abs(kappa_bounds[1] - kappa_bounds[0]) / num_cells_per_side, np.abs(kappa_bounds[1] - kappa_bounds[0]) / num_cells_per_side)
  )
  print(param_vals[0])
  print(kappa_vals[:, 0])
  if vs_beta:
    set_epsilon(0)
  else:
    set_beta(0)

  output_vals = []
  for kappa_val in kappa_vals[:, 0]:
    row = np.array([])
    for param_val in param_vals[0]:
      set_kappa(10 ** kappa_val)
      if vs_beta:
        set_beta(10 ** param_val)
      else:
        set_epsilon(10 ** param_val)
      row = np.append(row, output(iters))
    # print(row)
    output_vals.append(row)
    # print(output_vals)

  Z = np.asarray(output_vals)
  cf = ax.contourf(param_vals, kappa_vals, Z, levels=np.linspace(Z.min(), Z.max(), 8), cmap="YlOrRd")
  label = "beta" if vs_beta else "varepsilon"
  ax.set_xlabel(f"$\\log_{{10}}\\{label}$", fontsize="x-large")
  ax.set_ylabel("$\\log_{10}\\kappa$", fontsize="x-large")
  ax.set_xticks([param_bounds[0], 0, param_bounds[1]])
  ax.set_yticks([kappa_bounds[0], -1, kappa_bounds[1]])
  ax.tick_params(labelsize="x-large")
  ax.set_title("output", pad=10)
  return cf

from matplotlib.patches import ConnectionPatch

def plot_vs_isolated_params(metric_name="output", metric_fnc=output, enabled_params=(True, True), eps_max=100, beta_max=100, eps_min=0, beta_min=0, log_scale=False, width_factor=1, height_limit=None, line_offset=-0.15, axes=None, **kwargs):
  # fig, (ax1, ax2) = plt.subplots(1, 2)
  fig = plt.gcf()
  if axes == None:
    ax1 = plt.gca()
    ax2 = None
  elif len(axes) == 2:
    ax1 = axes[0]
    ax2 = axes[1]
  else:
    ax1 = axes[0]
    ax2 = None

  if enabled_params[0]:
    set_alpha(1)
    set_beta(0)

    if log_scale:
      eps_vals = np.array([])
      eps = eps_min
      while eps < eps_max:
        # print(f"Eps is now: {eps}")
        arr = np.linspace(eps, eps * 10, int(100 // eps))
        # print(arr)
        eps_vals = np.append(eps_vals, arr)
        eps *= 10
    else:
      eps_vals = np.linspace(eps_min, eps_max, 100)

    metric_vals = np.array([])
    max_val = 0.0
    max_eps_val = 0.0
    for eps_val in eps_vals:
      set_epsilon(eps_val)
      # print(f"Value appended at epsilon = {epsilon}")
      val = metric_fnc(**kwargs)
      if val > max_val:
        # print(f"new max val: {max_val}")
        max_val = val
        max_eps_val = epsilon
      metric_vals = np.append(metric_vals, val)
    print(f"Max {metric_name} = {max_val}, occurring at epsilon = {eps_vals[np.where(metric_vals == max_val)[0][0]]}")

    if log_scale:
      ax1.semilogx(eps_vals, metric_vals)
      ax1.set_xticks([0.01, 1, eps_max])
    else:
      ax1.plot(eps_vals, metric_vals)
      ax1.set_xticks([0, eps_max])
    ax1.set_xlabel("$\\epsilon$", fontsize="x-large")
    ax1.set_ylabel(metric_name, fontsize="x-large")
    # ax1.set_xticks([0.0, eps_max])
    ax1.set_yticks([0, np.round(max(metric_vals), 1)]) if height_limit == None else ax1.set_yticks([0, np.round(max(metric_vals), 1), height_limit])
    ax1.tick_params(labelsize="x-large")
    ax1.set_title(f"{metric_name} vs. $\\varepsilon$, $\\beta=0$", pad=10)
    # ax1.set_aspect(1.0/ax1.get_data_ratio(), adjustable='box')

  if enabled_params[1] and ax2 != None:
    set_alpha(1)
    set_epsilon(0)

    if log_scale:
      beta_vals = np.array([])
      beta = beta_min
      while beta < beta_max:
        beta_vals = np.append(beta_vals, np.linspace(beta, beta * 10, 10))
        beta *= 10
    else:
      beta_vals = np.linspace(beta_min, beta_max, 20)

    max_val = 0.0
    metric_vals = np.array([])
    for beta_val in beta_vals:
      set_beta(beta_val)
      # print(f"Value appended at epsilon = {epsilon}")
      val = metric_fnc(**kwargs)
      if val > max_val:
        max_val = val
      metric_vals = np.append(metric_vals, val)
    print(f"Max {metric_name} = {max_val}, occurring at beta = {np.where(metric_vals == max_val)}")

    if log_scale:
      ax2.semilogx(beta_vals, metric_vals)
      ax2.set_xticks([0.01, 1, beta_max])
    else:
      ax2.plot(beta_vals, metric_vals)
      ax2.set_xticks([0, beta_max])
    ax2.set_xlabel("$\\beta$", fontsize="x-large")
    ax2.tick_params(labelsize="x-large")

    # ax2.annotate(
    #   f"$\\kappa={kappa}$",
    #   xy=(1.02, 0.5),               # just outside the right edge, vertically centered
    #   xycoords="axes fraction",
    #   rotation=-90,                  # 90 degrees clockwise
    #   va="center",
    #   ha="left",
    #   fontsize="x-large",
    #   annotation_clip=False          # allows drawing outside the axes bounds
    # )
    ax2.set_title(f"{metric_name} vs. $\\beta$, $\\varepsilon=0$", pad=10)
    # ax2.set_ylim(0.0, ax1_max)
    # ax2.set_aspect(1.0/ax1.get_data_ratio(), adjustable='box')
    ax2.set_yticks([0, np.round(max(metric_vals), 1)])

  plt.tight_layout()

  # y_min = min(ax1.get_ylim()[0], ax2.get_ylim()[0])
  if ax2 != None:
    y_max = max(ax1.get_ylim()[1], ax2.get_ylim()[1]) if height_limit == None else height_limit
    ax1.set_ylim(0, y_max)
    ax2.set_ylim(0, y_max)

    # Draw the canvas so positions are finalized
    fig.canvas.draw()

    # Get current positions
    pos1 = ax1.get_position()
    pos2 = ax2.get_position()

    padding = 0.15
    if pos1.height >= pos2.height:
        ax1.set_position([pos1.x0, pos1.y0, pos1.width * width_factor, pos1.height])
        ax2.set_position([pos1.x0 + pos1.width * width_factor + padding, pos1.y0, pos2.width * width_factor, pos1.height])
    else:
        ax1.set_position([pos1.x0, pos2.y0, pos1.width * width_factor, pos2.height])
        ax2.set_position([pos1.x0 + pos1.width * width_factor + padding, pos2.y0, pos2.width * width_factor, pos2.height])

    xyA = (1e-3, y_max + line_offset)
    xyB = (0.99*beta_max, y_max + line_offset)
    con = ConnectionPatch(xyA=xyA, xyB=xyB, coordsA="data", coordsB="data",
                          axesA=ax1, axesB=ax2, color="gray", linestyle=(0, (5, 5)))
    ax2.add_artist(con)
    fig.canvas.draw()

  # plt.show()
  return max_eps_val

def plot_on_axis_profile(beta_val, eps_val, ax, color):
  z = np.linspace(0, 6, 60)
  neg_z = np.linspace(-3.5, 0, 35)

  set_epsilon(eps_val)
  set_beta(beta_val)
  set_kappa(1)

  ax.plot(neg_z, Chi(np.abs(neg_z), np.pi), color, label=f"$\\varepsilon={{{eps_val}}}, \\beta={{{beta_val}}}$")
  ax.plot(z, Chi(z, 0), color)
  # plt.text(1.05, text_pos, f"$\gamma_0$ = {gamma}", color=color, size="x-large")

# -*- coding: utf-8 -*-
"""PDE_Solver_v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ty5vXhw8V56M4YCy9-qM-lCyhUJhn0NF
"""

"""
Non-dimensionalized pheromone-enzyme system solver.

Spherical coordinates (r, theta) centered on cell of unit radius.
Domain: r in [1, r_max], theta in [0, pi].
theta = 0 points toward the external source.

Fields:
  Q(r) = gamma/r                     [known, harmonic]
  P(r,theta) = total external species [Laplace + point source, Robin BC]
  psi(r,theta) = complex concentration [nonlinear reaction-diffusion, Neumann BC]

Recovered fields:
  phi = Q - psi   (enzyme)
  chi = P - psi   (free pheromone)

Equations (boxed on whiteboard):
  (e):   nabla^2 Q = 0                 => Q = gamma/r
  (5+6): dr Q|_1 = -gamma
  (1):   nabla^2 P + 4*pi*alpha * delta^3(r - rho0 zhat) = 0
  (2+6): dr P|_1 = beta * [P(1,th) - psi(1,th)]
  (3):   nabla^2 psi + 4*pi*zeta * [(Q-psi)(P-psi) - kappa*psi] = 0
         dr psi|_1 = 0

Parameters:
  gamma = cell emission rate
  alpha = external source strength
  beta  = absorption rate at cell wall (Robin)
  zeta  = reaction rate
  kappa = dimensionless dissociation constant
  rho0  = source distance (in cell radii)
"""

import numpy as np
import matplotlib.pyplot as plt
from dataclasses import dataclass


@dataclass
class Params:
    gamma: float = 1.0
    alpha: float = 0.5
    beta:  float = 5.0
    zeta:  float = 5.0
    kappa: float = 0.2 # binding-unbinding of receptors on surface
    K: float = 1.0 # binding-unbinding of enzyme in medium
    rho0:  float = 5.0
    B0: float = 1.0

    def set_param (self, param, val):
      match param:
        case "gamma":
          self.gamma = val
        case "alpha":
          self.alpha = val
        case "beta":
          self.beta = val
        case "zeta":
          self.zeta = val
        case "kappa":
          self.kappa = val
        case "K":
          self.K = val
        case "rho0":
          self.rho0 = val
        case "B0":
          self.B0 = val
        case _:
          print("Warning: Not a valid parameter")

    def print_params(self):
      print(self.gamma, self.alpha, self.beta, self.zeta, self.kappa, self.K, self.rho0, self.B0)


@dataclass
class Grid:
    r_max: float = 15.0
    N_r:     int = 140
    N_theta: int = 80


class PheromoneEnzymeSolver:
    GREEK_LETTERS = {
      "alpha":   ("α", "Α"),
      "beta":    ("β", "Β"),
      "gamma":   ("γ", "Γ"),
      "delta":   ("δ", "Δ"),
      "epsilon": ("ε", "Ε"),
      "zeta":    ("ζ", "Ζ"),
      "eta":     ("η", "Η"),
      "theta":   ("θ", "Θ"),
      "iota":    ("ι", "Ι"),
      "kappa":   ("κ", "Κ"),
      "lambda":  ("λ", "Λ"),
      "mu":      ("μ", "Μ"),
      "nu":      ("ν", "Ν"),
      "xi":      ("ξ", "Ξ"),
      "omicron": ("ο", "Ο"),
      "pi":      ("π", "Π"),
      "rho":     ("ρ", "Ρ"),
      "sigma":   ("σ", "Σ"),
      "tau":     ("τ", "Τ"),
      "upsilon": ("υ", "Υ"),
      "phi":     ("φ", "Φ"),
      "chi":     ("χ", "Χ"),
      "psi":     ("ψ", "Ψ"),
      "omega":   ("ω", "Ω"),
    }

    def __init__(self, params: Params, grid: Grid, show_plots=False, debug=False):
        self.p = params
        self.g = grid

        self.dr     = (grid.r_max - 1.0) / grid.N_r
        self.dtheta = np.pi / grid.N_theta

        # Cell-centred coordinates
        self.r     = 1.0 + (np.arange(grid.N_r) + 0.5) * self.dr
        self.theta = (np.arange(grid.N_theta) + 0.5) * self.dtheta
        self.R, self.THETA = np.meshgrid(self.r, self.theta, indexing='ij')

        # Precomputed trig
        self.SIN_TH = np.sin(self.THETA)
        self.COS_TH = np.cos(self.THETA)

        # Face values of sin(theta) for conservative angular differencing
        self.theta_faces = np.arange(grid.N_theta + 1) * self.dtheta  # 0 to pi
        self.sin_faces   = np.sin(self.theta_faces)  # sin(0)=0, sin(pi)=0

        # Known field
        self.Q = params.gamma / self.R

        self._build_source()

        self.show_plots = show_plots

        self.debug = debug
        if self.debug:
          print("r", self.r)
          print("theta", self.theta)
          print("R", self.R)
          print("THETA", self.THETA)
          print("SIN_THETA", self.SIN_TH)
          print("COS_THETA", self.COS_TH)
          print("theta faces", self.theta_faces)
          print("sin_faces", self.sin_faces)

    # ------------------------------------------------------------------
    def _build_source(self):
        """Regularised point source at (r=rho0, theta=0)."""
        p = self.p
        sig_r  = 2.0 * self.dr
        sig_th = 2.0 * self.dtheta
        g_r  = np.exp(-0.5 * ((self.R - p.rho0) / sig_r)**2)
        g_th = np.exp(-0.5 * (self.THETA / sig_th)**2)
        raw = g_r * g_th
        # Normalise: integral of S_P * r^2 sin(theta) dr dtheta dphi = 4*pi*alpha
        # With 2*pi from phi integral:
        integral = np.sum(raw * 2 * np.pi * self.R**2 * self.SIN_TH) \
                   * self.dr * self.dtheta
        self.S_P = raw * (4 * np.pi * p.alpha) / integral

    # ------------------------------------------------------------------
    def _angular_laplacian(self, f):
        """
        (1 / (r^2 sin(theta))) d/dtheta [sin(theta) df/dtheta]

        Conservative finite differences using face values of sin(theta).
        At theta=0 and theta=pi the faces have sin=0, so the flux
        vanishes automatically — no special pole treatment needed.
        """
        N_th = self.g.N_theta
        dth  = self.dtheta

        # Angular flux at faces: sin(theta_face) * df/dtheta
        flux = np.zeros((self.g.N_r, N_th + 1))
        flux[:, 1:-1] = self.sin_faces[1:-1][np.newaxis, :] \
                         * (f[:, 1:] - f[:, :-1]) / dth
        # flux at theta=0 and theta=pi: sin=0, so flux=0 (already zero)

        # Divergence: (1/(r^2 sin(theta))) * d(flux)/dtheta
        return (flux[:, 1:] - flux[:, :-1]) / (dth * self.R**2 * self.SIN_TH)

    # ------------------------------------------------------------------
    def _radial_laplacian(self, f, f_ghost_inner, f_ghost_outer):
        """
        (1/r^2) d/dr(r^2 df/dr) = d^2f/dr^2 + (2/r) df/dr
        """
        dr = self.dr
        r  = self.R

        f_ext = np.concatenate([f_ghost_inner[np.newaxis, :],
                                f,
                                f_ghost_outer[np.newaxis, :]], axis=0)

        d2f = (f_ext[2:, :] - 2*f_ext[1:-1, :] + f_ext[:-2, :]) / dr**2
        df  = (f_ext[2:, :] - f_ext[:-2, :]) / (2 * dr)

        return d2f + (2.0 / r) * df

    # ------------------------------------------------------------------
    def laplacian(self, f, bc_type='neumann'):
        """
        Full spherical Laplacian with boundary conditions.
        bc_type: 'neumann' or ('robin', P, psi)
        """
        # Outer BC: Dirichlet f=0
        f_ghost_outer = -f[-1, :]

        # Inner BC
        if bc_type == 'neumann':
            f_ghost_inner = f[0, :]
        elif bc_type[0] == 'robin':
            _, P, psi = bc_type
            b  = self.p.beta
            dr = self.dr
            f_ghost_inner = (P[0, :] * (1 - dr*b/2) + dr*b * psi[0, :]) \
                            / (1 + dr*b/2)
        else:
            raise ValueError(f"Unknown bc_type: {bc_type}")

        return self._radial_laplacian(f, f_ghost_inner, f_ghost_outer) \
               + self._angular_laplacian(f)

    # ------------------------------------------------------------------
    def solve(self, max_iter=200000, tol=5e-8, print_every=10000):
        p = self.p

        # CFL: radial diffusion ~ 1/dr^2, angular ~ 1/(r_min^2 * dtheta^2)
        dt = 0.3 * self.dr**2 * self.dtheta**2 \
             / (2 * (self.dr**2 + self.dtheta**2))

        # Initialise P from free-space point source
        dist = np.sqrt(self.R**2 + p.rho0**2
                       - 2 * self.R * p.rho0 * self.COS_TH)
        dist = np.maximum(dist, 0.1)
        P   = p.alpha / dist
        psi = np.zeros_like(P)
        # print(type(psi))
        # print(type(P))

        for n in range(max_iter):
            lap_P   = self.laplacian(P,   bc_type=('robin', P, psi))
            lap_psi = self.laplacian(psi, bc_type='neumann')

            dPdt    = lap_P + self.S_P
            rxn     = 4*np.pi*p.zeta * ((self.Q - psi)*(P - psi) - p.K*psi)
            dpsi_dt = lap_psi + rxn

            P_new   = P   + dt * dPdt
            psi_new = psi + dt * dpsi_dt

            psi_new = np.clip(psi_new, 0, np.minimum(self.Q, np.maximum(P, 0)))
            P_new   = np.maximum(P_new, 0)

            if n % print_every == 0:
                change = max(np.max(np.abs(P_new - P)),
                             np.max(np.abs(psi_new - psi)))
                print(f"  iter {n:7d}, max |dF| = {change:.3e}")
                if change < tol:
                    print(f"  converged at {n}")
                    break

            P, psi = P_new, psi_new

        self.P   = P
        self.psi = psi
        self.phi = self.Q - psi
        self.chi = P - psi
        if self.debug:
          print("P", P)
          print("Q", self.Q)
          print("psi", psi)
          print("chi", self.chi)
          print("phi", self.phi)
        return P, psi

    # ------------------------------------------------------------------
    def bound_snr(self):
        """
        Signal-to-noise ratio for directional sensing at the cell surface.

            SNR = int dOmega chi(1, theta) cos(theta)
                  / sqrt( int dOmega chi(1, theta) )

        where dOmega = sin(theta) dtheta dphi, and the phi integral gives 2*pi.

        The numerator measures the dipole moment of chi on the cell wall
        (how much signal distinguishes front from back).
        The denominator is sqrt of total signal (Poisson shot noise scaling).
        """
        p = self.p
        chi_surface = self.chi[0, :]     # chi at r = r_min (closest to cell wall)
        sin_th      = np.sin(self.theta)
        cos_th      = np.cos(self.theta)
        dth         = self.dtheta
        if self.debug:
          print("Chi at surface: ", chi_surface)
          print("Sin theta: ", sin_th)
          print("Cos theta: ", cos_th)
          print("Dth", dth)

        bound_complex = p.B0 * chi_surface / (chi_surface + p.kappa)

        # int dOmega f(theta) = 2*pi * int_0^pi f(theta) sin(theta) dtheta
        numerator   = 2 * np.pi * np.sum(bound_complex * cos_th * sin_th) * dth
        denominator = np.sqrt(2 * np.pi * np.sum(bound_complex * sin_th) * dth)

        return numerator / denominator

    # ------------------------------------------------------------------
    def snr(self):
        """
        Signal-to-noise ratio for directional sensing at the cell surface.

            SNR = int dOmega chi(1, theta) cos(theta)
                  / sqrt( int dOmega chi(1, theta) )

        where dOmega = sin(theta) dtheta dphi, and the phi integral gives 2*pi.

        The numerator measures the dipole moment of chi on the cell wall
        (how much signal distinguishes front from back).
        The denominator is sqrt of total signal (Poisson shot noise scaling).
        """
        chi_surface = self.chi[0, :]     # chi at r = r_min (closest to cell wall)
        sin_th      = np.sin(self.theta)
        cos_th      = np.cos(self.theta)
        dth         = self.dtheta
        if self.debug:
          print("Chi at surface: ", chi_surface)
          print("Sin theta: ", sin_th)
          print("Cos theta: ", cos_th)
          print("Dth", dth)

        # int dOmega f(theta) = 2*pi * int_0^pi f(theta) sin(theta) dtheta
        numerator   = 2 * np.pi * np.sum(chi_surface * cos_th * sin_th) * dth
        denominator = np.sqrt(2 * np.pi * np.sum(chi_surface * sin_th) * dth)

        return numerator / denominator

    # ==================================================================
    # Plotting
    # ==================================================================
    def _pad_to_poles(self, field):
        """Pad field with extra columns at theta=0 and theta=pi."""
        return np.concatenate([field[:, :1], field, field[:, -1:]], axis=1)

    def _padded_cylindrical(self):
        """Padded (r, theta) grid mapped to (z, rho_cyl)."""
        theta_pad = np.concatenate([[0.0], self.theta, [np.pi]])
        r = self.r
        R_pad, TH_pad = np.meshgrid(r, theta_pad, indexing='ij')
        Z_pad   = R_pad * np.cos(TH_pad)
        RHO_pad = R_pad * np.sin(TH_pad)
        return Z_pad, RHO_pad

    def plot_2d(self, savepath=None):
        Z, RHO = self._padded_cylindrical()

        fields = [
            (self._pad_to_poles(self.phi), 'φ (enzyme)'),
            (self._pad_to_poles(self.chi), 'χ (free pheromone)'),
            (self._pad_to_poles(self.psi), 'ψ (complex)'),
            (self._pad_to_poles(self.P),   'P = χ + ψ'),
        ]

        th = np.linspace(0, 2*np.pi, 200)
        cell_z, cell_rho = np.cos(th), np.sin(th)

        fig, axes = plt.subplots(2, 2, figsize=(14, 10))

        for ax, (field, title) in zip(axes.flat, fields):
            ax.pcolormesh(Z, RHO, field, shading='gouraud', cmap='YlOrBr')
            im = ax.pcolormesh(Z, -RHO, field, shading='gouraud', cmap='YlOrBr')
            ax.plot(cell_z, cell_rho, 'k-', lw=1.5)
            ax.plot(self.p.rho0, 0, 'k+', ms=10, mew=2)
            ax.set_xlim(-5, self.p.rho0 + 3)
            ax.set_ylim(-4, 6)
            ax.set_xlabel('z')
            ax.set_ylabel('ρ')
            ax.set_title(title)
            ax.set_aspect('equal')
            plt.colorbar(im, ax=ax, shrink=0.8)

        plt.tight_layout()
        plt.show()
        if savepath:
            plt.savefig(savepath, dpi=150, bbox_inches='tight')
            plt.close()

    def plot_axis(self, axes, color="blue", savepath=None):
        # j_axis = [0, -1]  # theta closest to 0 AND pi (toward AND away from source)
        ax = axes
        p = self.p
        plt.gcf().set_size_inches(10, 6)
        min_r_index = np.where(self.r >= self.p.rho0)[0][0]
        max_r_index = np.where(self.r >= self.p.rho0 + 2)[0][0]
        print(self.r[min_r_index])
        print(self.r[max_r_index])
        # ax.plot(self.r[:max_r_index], self.phi[:max_r_index, 0], 'r-',  lw=2, label='φ (enzyme)')
        # ax.plot(-self.r[:min_r_index], self.phi[:min_r_index, -1], 'r-',  lw=2)
        ax.plot(self.r[:max_r_index], self.chi[:max_r_index, 0], color=color,  lw=2, label=f"$\\beta={{{p.beta}}}, $\\gamma={{{p.gamma}}}, $K={{{p.K}}}")
        ax.plot(-self.r[:min_r_index], self.chi[:min_r_index, -1], color=color,  lw=2)
        # ax.plot(self.r[:max_r_index], self.psi[:max_r_index, 0], 'g-',  lw=2, label='ψ (complex)')
        # ax.plot(-self.r[:min_r_index], self.psi[:min_r_index, -1], 'b-',  lw=2)
        # ax.plot(self.r[:max_r_index], self.Q[:max_r_index, 0],   'r--', lw=1, alpha=0.4, label='Q = φ+ψ')
        # ax.plot(-self.r[:min_r_index], self.Q[:min_r_index, -1], 'r--',  lw=2)
        # ax.plot(self.r[:max_r_index], self.P[:max_r_index, 0],   'b--', lw=1, alpha=0.4, label='P = χ+ψ')
        # ax.plot(-self.r[:min_r_index], self.P[:min_r_index, -1], 'b--',  lw=2,)
        ax.set_ylim(bottom=0)
        # plt.tight_layout()
        # plt.show()
        if savepath:
            plt.savefig(savepath, dpi=150)
            plt.close()

    def plot_surface(self, savepath=None):
        theta_deg = np.degrees(self.theta)
        fig, ax = plt.subplots(figsize=(10, 6))
        ax.plot(theta_deg, self.phi[0, :], 'r-', lw=2, label='φ (enzyme)')
        ax.plot(theta_deg, self.chi[0, :], 'b-', lw=2, label='χ (free pheromone)')
        ax.plot(theta_deg, self.psi[0, :], 'g-', lw=2, label='ψ (complex)')
        ax.set_xlabel('θ (degrees from source)')
        ax.set_ylabel('Concentration at cell surface')
        ax.set_title('Angular profile on cell wall')
        ax.legend()
        ax.set_ylim(bottom=0)
        plt.tight_layout()
        plt.show()
        if savepath:
            plt.savefig(savepath, dpi=150)
            plt.close()


    def greek(self, s: str) -> str:
      """Convert a romanized Greek letter name to its Unicode symbol.

      Capitalization rules:
          - ALL CAPS  (e.g. "ALPHA") → uppercase Greek letter (Α)
          - Title case (e.g. "Alpha") → uppercase Greek letter (Α)
          - Anything else (e.g. "alpha") → lowercase Greek letter (α)

      Returns None if the string is not a recognized Greek letter name.
      """
      key = s.strip().lower()
      if key not in self.GREEK_LETTERS:
          return s

      lower, upper = self.GREEK_LETTERS[key]
      if s.isupper() or (s[0].isupper() and s[1:].islower()):
          return upper
      return lower

    def plot_metric_heatmap (self, name="SNR", fnc=snr, param1="beta", param2="zeta", param1_max=5, param2_max=5, num_cells_per_side=25, ax=None, show_max=False, **kwargs):
      param1_vals, param2_vals = np.meshgrid(np.logspace(-2, np.log10(param1_max), num=num_cells_per_side), np.arange(0, param2_max, param2_max / num_cells_per_side))
      print(param1_vals)
      print(param2_vals)
      vals = []

      max_val = 0
      max_param1 = 0
      max_param2 = 0

      for param2_val in param2_vals[:, 0]:
        row = np.array([])
        for param1_val in param1_vals[0]:
          self.p.set_param(param1, param1_val)
          self.p.set_param(param2, param2_val)

          self._build_source()
          self.p.print_params()
          print(f"Current iteration: {param1} = {param1_val}, {param2} = {param2_val}")
          self.solve(max_iter=50000, tol=1e-7)
          self.plot_2d()
          val = fnc(self)
          print("SNR: ", val)
          if val > max_val:
            max_param1 = param1_val
            max_param2 = param2_val
            max_val = val
          row = np.append(row, val)
        vals.append(row)

      img = ax.imshow(np.asarray(vals), extent=[0, param1_max, 0, param2_max], cmap="YlOrBr", origin='lower')
      print(f"Max {name} = ({max_val}), reached at {param1} = {max_param1}, {param2} = {max_param2}")
      if show_max:
        ax.plot(max_param1, max_param2, 'x')
      ax.set_xlabel(f"{self.greek(param1)}", fontsize="x-large")
      # label = "$\\sqrt{{\\varepsilon}}$" if sqrt_eps else "$\\varepsilon$"
      ax.set_ylabel(f"{self.greek(param2)}", fontsize="x-large")
      ax.set_xticks([0, param1_max])
      ax.set_yticks([0, param2_max])
      ax.tick_params(labelsize="x-large")
      ax.set_title(name, pad=10)
      if param1_max > param2_max:
        ax.set_aspect(max(param1_max, param2_max) / min(param1_max, param2_max))
      else:
        ax.set_aspect(min(param1_max, param2_max) / max(param1_max, param2_max))

      return img

    def max_metric_val (self, fnc=snr, param1="beta", param2="zeta", param1_max=5, param2_max=5, num_cells_per_side=25, **kwargs):
      param1_vals, param2_vals = np.meshgrid(np.logspace(-2, np.log10(param1_max), num=num_cells_per_side), np.arange(0, param2_max, param2_max / num_cells_per_side))
      print(param1_vals)
      print(param2_vals)
      vals = []

      max_val = 0
      max_param1 = 0
      max_param2 = 0

      for param2_val in param2_vals[:, 0]:
        row = np.array([])
        for param1_val in param1_vals[0]:
          self.p.set_param(param1, param1_val)
          self.p.set_param(param2, param2_val)

          self.Q = self.p.gamma / self.R
          self._build_source()
          self.p.print_params()
          # print(f"Current iteration: {param1} = {param1_val}, {param2} = {param2_val}")
          self.solve(max_iter=50000, tol=1e-7)
          # self.plot_2d()
          val = fnc(self)
          print("SNR: ", val)
          if val > max_val:
            max_param1 = param1_val
            max_param2 = param2_val
            max_val = val
          row = np.append(row, val)
        vals.append(row)
        print(f"So far: Max val = {max_val}, reached at {param1} = {max_param1}, {param2} = {max_param2}")


      print(f"Final: Max val = {max_val}, reached at {param1} = {max_param1}, {param2} = {max_param2}")
      return max_param1, max_param2, max_val

    def max_val_for_multiple_kappas(self, kappa_min, kappa_max, param1="beta", param2="zeta", metric_fnc=bound_snr):
      num_kappas = 10
      num_cells = 5
      kappa_vals = np.logspace(kappa_min, kappa_max, num_kappas)

      data = []
      max_param1_vals = []
      max_param2_vals = []
      for val in kappa_vals:
        print(f"Kappa = {val}")
        self.p.set_param("kappa", val)
        max_param1, max_param2, max_val= self.max_metric_val(metric_fnc, param1, param2, num_cells_per_side=num_cells)
        max_param1_vals.append(max_param1)
        max_param2_vals.append(max_param2)
        data.append(max_val)

      plt.rcParams.update({'font.size': 22})
      sc = plt.scatter(max_param1_vals, max_param2_vals, c=kappa_vals, cmap="YlOrBr", norm="log")
      plt.xlabel(param1)
      plt.ylabel(param2)
      plt.gcf().colorbar(sc)
      plt.savefig(f"bound SNR for {param2} and {param1} - {num_kappas} kappas from {10 ** kappa_min} to {10 ** kappa_max} - {num_cells} cells per param.png")

if __name__ == "__main__":
    params = Params(
        gamma = 1.0,
        alpha = 1.0,
        beta  = 1.0,
        zeta  = 0.02,
        K = 1.0,
        kappa = 1.0,
        rho0  = 4.0,
    )
    grid = Grid(r_max=15.0, N_r=140, N_theta=80)

    solver = PheromoneEnzymeSolver(params, grid)
    solver.solve(max_iter=50000, tol=5e-8, print_every=10000)

    ax = plt.gca()
    solver.plot_axis(ax, color="blue")

    plot_on_axis_profile(0, 0, ax, "black")
    plot_on_axis_profile(1, 1, ax, "orange")

    ax.axvline(x=1, color='gray', ls=':', alpha=0.5, label='Cell wall')
    ax.axvline(x=params.rho0, color='gray', ls='--', alpha=0.5,
                label=f'Source (ρ₀={params.rho0})')
    ax.set_xlabel('r')
    ax.set_ylabel('Concentration')
    ax.set_title('On-axis profiles (θ=0 and θ=pi)')
    ax.legend()

    plt.tight_layout()
    plt.show()

