# -*- coding: utf-8 -*-
"""EqualFooting_PlotReproduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCqFw6qzmg_qNuAKy8W8-kvjuzC2paFZ
"""

from scipy.special import iv, kv, ive, kve, gammaln, gamma, legendre
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

rho_0 = 4
epsilon = 0.05 # Strength of diffusive degradation
arg_0 = 2 * epsilon * np.sqrt(rho_0)
arg_e = 2 * epsilon
alpha = 1 # Strength of secretion
beta = 1 # Strength of degradation at surface
B0 = 1 # Number of ligand receptors at cell surface
pole_tolerance = 1
lim_tol = 1e-05
zero_tol = 1e-300 # For comparing numbers with 0, because these Bessels get ridiculously tiny with small epsilon
# How did Claude know to use 300? Answer: It was essentially arbitrary

def set_epsilon(val):
  global epsilon, arg_0, arg_e
  epsilon = val
  arg_0 = 2 * epsilon * np.sqrt(rho_0)
  arg_e = 2 * epsilon

def set_rho_0(val):
  global rho_0, arg_0
  rho_0 = val
  arg_0 = 2 * epsilon * np.sqrt(rho_0)

def set_beta(val):
  global beta
  beta = val

def set_B0(val):
  global B0
  B0 = val

def set_lim_tol(val):
  global lim_tol
  lim_tol = val

# Update 5/14/26: Tried these small-arg expansions when epsilon gets small, they don't seem to work effectively;
# probably because they keep canceling each other out in the denominator.

# Edit: Nevermind, when sticking with the regular iv and kv fncs for small args, zero terms are still appearing left and right
# in the denominator of X_l, but none of the Chi values are negative anymore. Not sure why this is happening
# but I think I'll stick with the regular fncs from now on.

# So ok. I'm sticking with the regular fncs. Why are all these 0s still appearing in the denominator of X_l?
# Question 1: Does it matter? Even for normal-sized epsilon, these zeros are still appearing, and the graph
# looked fine. Examining the graph more closely - I'll test for theta behind the cell next and see if the Chis become negative.
# Also, for what it's worth, the iv / kv ratio never seems to be close to zero, which means the denominator
# as a whole is evaluating to close to zero, which is unfortunate cause it makes it a lot harder to debug :(

# Alright, Chi(3, 135) is sus af with the oscillation btwn iterations but actually all these Chis are evaluating
# to positive values which is really good! What to try next?

# Next, ignoring the zero in denom problem for a second, I want to confirm that a higher epsilon leads to
# a lower peak Chi value (or doesn't affect the peak, rather than increase it)
# This is confirmed!

# Ok, so the zero in denominator in X_l is still weird, and I'll definitely come back to it should the need
# arise, but for now by setting the iterations to 50, as demonstrated by my debug plots, the heatmaps converge
# without a problem! Well, sort of; the far field solution is everywhere 0 ( ಠ ͜ʖಠ)

# Oh yeah, also, epsilon still cannot be exactly 0 or else X_l just goes straight to NaN. How to fix...

# Update: The log approximation for the ratio was also breaking the far field solutions. Gemini is apparently pretty useless when it comes to this stuff.

# Now that I've returned everything back to just standard functions, and simply reduced the iterations, the heatmaps are more or less working.
# Here are some observations:
# - The effects of beta almost completely disappear when epsilon is 1, although they are still visible if scrutinizing closely.
# - For eventual publication, might have to figure out how to get rid of that ring artifact at the boundary between the near and far field solutions? Maybe
#   use the averages idea I was talking about? For now though, not a problem.
# - Increasing epsilon leads to a sharper decay in concentration close to the source, and additionally reduces the amplitude of concentration at all points.
# - This one might be an issue: Increasing epsilon leads to concentration values going below 0, which shouldn't really be legal.

# LEAVE-OFF POINT 5/14/26. TODO: Check debug Chi convergence graphs for epsilon = 1 to see if there are any negative values, or if those negatives are just a
# result of the artifacts. If the negative values do exist, this either means epsilon cannot go above a certain max range or the code is broken.
# Think about which one is more likely later.

# 5/15 Start

# Ok, update: The reason why there is a ring artifact in the heatmap at rho = rho_0 is because the series does not converge there, but oscillates
# back and forth probably at a frequency determined by the angle. So, after a certain number of iterations, when it is stopped, it will be
# at a random point in its oscillation - except those artifacts aren't random, are they. So probably a predictable point in its oscillation
# which leads to the artifact. Again, probably don't need to worry about this now but just an observation.

# Also, this is now confirmed why the epsilon < 0 issue is happening: sometimes, when the oscillation is stopped, its value will happen to
# be below 0 at that point. Now that I've confirmed this, I think it's still best to circle back to this issue as it does not impact the anisostropy,
# which is the focus for the next tasks.

def log_iv_over_kv(nu, x):
    """log( iv(nu,x) / kv(nu,x) ) computed stably for any x >= 0."""
    if np.isclose(epsilon, 0., atol=zero_tol):
        # small-argument asymptotics in log-space
        # log iv(nu,x) ~ nu*log(x/2) - gammaln(nu+1)
        # log kv(nu,x) ~ gammaln(nu) - nu*log(x/2) - log(2)   (nu > 0)
      log_iv = nu * np.log(x / 2) - gammaln(nu + 1)
      log_kv = gammaln(nu) - nu * np.log(x / 2) - np.log(2)
      return log_iv - log_kv
    # general: use scaled functions, ratio of ive/kve times exp(-2x)
    # ive = iv*exp(-x), kve = kv*exp(x)  =>  iv/kv = (ive/kve)*exp(-2x)
    log_ratio = np.log(ive(nu, x)) - np.log(kve(nu, x)) + 2 * x
    return log_ratio

def iv_over_kv(nu, x):
    return np.exp(log_iv_over_kv(nu, x))

def iv_kv_sum(nu, x):
    ive_sum = ive(nu - 1, x) + ive(nu + 1, x)
    kve_sum = kve(nu - 1, x) + kve(nu + 1, x)
    return ive_sum, kve_sum

# ── X_l ──────────────────────────────────────────────────────────────────────

def X_l(l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return X_l_limit(l)

    order = 2 * l + 1
    arg   = arg_0

    log_r    = log_iv_over_kv(order, arg)
    ratio    = np.exp(log_r) # keep for diagnostics

    ive_sum, kve_sum = iv_kv_sum(order, arg)
    inner = np.exp(log_r) * kve_sum + np.exp(2 * arg) * ive_sum

    # if np.isclose(inner, 0.0, atol=zero_tol):
    #     if np.isclose(ratio, 0, atol=zero_tol):
    #         print(f"Zero denominator and zero iv/kv in X_l at l={l}")
    #     else:
    #         print(f"Zero denominator in X_l at l={l}")
    # elif np.isclose(ratio, 0, atol=zero_tol):
    #     print(f"Zero iv/kv in X_l at l={l}")

    # X_l = 2*order*alpha / (sqrt(epsilon)*rho_0) / denom
    #      = 2*order*alpha / (sqrt(epsilon)*rho_0) * exp(arg) / inner
    prefactor = 2 * order * alpha / (epsilon * rho_0)
    return prefactor * np.exp(arg) / inner


# ── Y_l ──────────────────────────────────────────────────────────────────────

def Y_l(l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return Y_l_limit(l)

    order = 2 * l + 1
    arg   = arg_e

    ive_sum_e, kve_sum_e = iv_kv_sum(order, arg)
    two_beta_1 = 2 * beta + 1
    # sq_eps     = np.sqrt(epsilon)

    numer_scaled = two_beta_1 * ive(order, arg) - epsilon * ive_sum_e
    denom_scaled = two_beta_1 * kve(order, arg) + epsilon * kve_sum_e

    if np.isclose(denom_scaled, 0.0, atol=zero_tol):
        raise Exception("Zero denominator in Y_l (scaled)")

    ratio_nd = numer_scaled / denom_scaled

    return -X_l(l) * ratio_nd * np.exp(2 * arg)


# ── Z_l ──────────────────────────────────────────────────────────────────────

def Z_l(l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return Z_l_limit(l)

    order = 2 * l + 1
    log_r0 = log_iv_over_kv(order, arg_0)
    return X_l(l) * np.exp(log_r0) + Y_l(l)


# ── radial functions ──────────────────────────────────────────────────────────

def R_l_lt(rho, l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return R_l_lt_limit(rho, l)
    order = 2 * l + 1
    arg   = 2 * epsilon * np.sqrt(rho)
    return (X_l(l) * ive(order, arg) * np.exp(arg)
            + Y_l(l) * kve(order, arg) * np.exp(-arg)) / np.sqrt(rho)


def R_l_gt(rho, l):
    if np.isclose(epsilon, 0., atol=lim_tol):
        return R_l_gt_limit(rho, l)
    order = 2 * l + 1
    arg   = 2 * epsilon * np.sqrt(rho)
    return Z_l(l) * kve(order, arg) * np.exp(-arg) / np.sqrt(rho)


# ── limiting cases ──────────────────────────────────────────────────────────

def X_l_limit (l):
  return alpha / rho_0 ** (l + 1)

def Y_l_limit (l):
  return X_l_limit(l) * (l - beta) / (l + beta + 1)

def Z_l_limit (l):
  return X_l_limit(l) * rho_0 ** (2*l + 1) + Y_l_limit(l)

def R_l_lt_limit (rho, l):
  return X_l_limit(l) * rho ** l + Y_l_limit(l) / rho ** (l + 1)

def R_l_gt_limit (rho, l):
  return Z_l_limit(l) / rho ** (l + 1)

def is_near_pole (rho, theta):
  if np.abs(rho) < pole_tolerance: return True
  x = rho * np.sin(theta)
  z = rho * np.cos(theta)
  if np.sqrt(x**2 + (z-rho_0)**2) < pole_tolerance: return True
  return False

def R_l (rho, theta, l):
  if is_near_pole(rho, theta):
    return np.nan
  val = R_l_lt(rho, l) if rho <= rho_0 else R_l_gt(rho, l)
  return val

vR_l = np.vectorize(R_l)

# LEAVE-OFF POINT LUNCH 6/11/26: Did I fuck up the derivations? Might need to go back and double check.
# Just remember: Sqrt of the old epsilon is the new epsilon, and the old epsilon = the new epsilon^2.

def Chi (rho, theta, n=25, debug=False):
  sol = 0
  for l in range(n):
    P_l = legendre(l)
    sol += vR_l(rho, theta, l) * P_l(np.cos(theta))
  # print(sol)
  # if debug and sol < 0: sol = 0
  # if sol < 0: print(f"Warning: $\\chi$({rho},{theta}) = {sol} < 0 after {n} iterations")
  return sol

set_rho_0(4)
# Problem: Lefebre says G - F > 0 when rho_0 > 2, but mine only satisfies
# the same inequality when rho_0 > 2.5

F = ( rho_0 ** 2 * (rho_0 - 1) ) / (rho_0*(rho_0-1) - 1) - np.log(rho_0) / 2 + np.log( (rho_0*(rho_0-1) - 1) / (rho_0*(rho_0-1)) ) / 2

G = ( (rho_0+1)*(rho_0**2 + rho_0 - 1) + rho_0) / (rho_0*2 + rho_0 + 1) - np.log(rho_0+1) / 2 + np.log( (rho_0**2 + rho_0 - 1) / (rho_0*(rho_0+1)) ) / 2

def set_alpha(val):
  global alpha, F, G
  alpha = val

  F = ( rho_0 ** 2 * (rho_0 - 1) ) / (rho_0*(rho_0-1) - 1) - np.log(rho_0) / 2 + np.log( (rho_0*(rho_0-1) - 1) / (rho_0*(rho_0-1)) ) / 2
  G = ( (rho_0+1)*(rho_0**2 + rho_0 - 1) + rho_0) / (rho_0*2 + rho_0 + 1) - np.log(rho_0+1) / 2 + np.log( (rho_0**2 + rho_0 - 1) / (rho_0*(rho_0+1)) ) / 2

def Anisotropy ():
  return R_l_lt(1, 1) / (R_l_lt(1, 0) * 3)

def Anisotropy_Lefebre() :
  numer = 2 + epsilon*(G-F)*(rho_0**2 - 1)
  denom = 3*( 2*rho_0 - epsilon*(F+G)*(rho_0**2 - 1) )
  return numer / denom

kappa = 1

def set_kappa(val):
  global kappa
  kappa = val

def Chi_front (n=25):
  sum = 0
  for l in range(1, n, 1):
    sum += ( 1 / (2*l+1) ) * R_l_lt(1, l) * (legendre(l+1)(0)-legendre(l-1)(0)) # This method of calling Legendres works
  return 2*np.pi*( R_l_lt(1, 0) - sum )

def Chi_back (n=25):
  sum = 0
  for l in range(1, n, 1):
    sum += ( 1 / (2*l+1) ) * R_l_lt(1, l) * (legendre(l+1)(0)-legendre(l-1)(0))
  return 2*np.pi*( R_l_lt(1, 0) + sum )

def g_abs ():
  return 4*np.pi*R_l_lt(1, 0)

def g_rel (n=25):
  return (Chi_front(n) - Chi_back(n)) / Chi_back(n)

def output (n=25):
  return Chi_front(n) / (Chi_front(n)+kappa) - Chi_back(n) / (Chi_back(n)+kappa)

def bound_complex (theta, n=25):
  return B0 * Chi(1, theta, n) / ( Chi(1, theta, n) + kappa)

def bound_SNR (n=25):
  theta_vals = np.arange(0, np.pi, np.deg2rad(1))
  dth = theta_vals[1] - theta_vals[0]

  b_vals = np.array([bound_complex(theta, n) for theta in theta_vals])
  jacobian = np.sin(theta_vals)

  numer = np.sum(b_vals * np.cos(theta_vals) * jacobian) * dth * 2 * np.pi
  denom = np.sum(b_vals * jacobian) * dth * 2 * np.pi
  denom = np.sqrt(denom)

  return numer / denom

def SNR (use_avg, n=25):
  if use_avg:
    return ( Chi_front(n) - Chi_back(n) ) / np.sqrt( Chi_front(n) + Chi_back(n) )
  else:
    chi_f = Chi(1, 0, n)
    chi_b = Chi(1, np.pi, n)
    return ( chi_f - chi_b ) / np.sqrt( chi_f + chi_b )

def fake_SNR (n=25):
  chi_f = Chi(1, 0, n)
  chi_b = Chi(1, np.pi, n)
  return ( chi_f - chi_b ) / (chi_f + chi_b)

def new_SNR ():
  return R_l_lt(1, 1) / np.sqrt(R_l_lt(1, 0))

def new_new_SNR ():
  return ( X_l(1) * ive(3, arg_e) * np.exp(arg_e) + Y_l(1) * kve(3, arg_e) * np.exp(-arg_e) ) \
    / np.sqrt ( X_l(0) * ive(1, arg_e) * np.exp(arg_e) + Y_l(0) * kve(1, arg_e) * np.exp(-arg_e) )

def reset():
  set_beta(0)
  set_epsilon(0)
  set_kappa(1)
  set_B0(1)

# Because of the nature of the X_l term, for small epsilon stuff keeps breaking after many iterations. The purpose of this cell is
# to figure out exactly what is breaking so I can fix it.

def test_Chi(theta, n=25):
  print("Theta = ", theta, ", num iters = ", n)
  for rho in range(5):
    print(f"Chi({rho}, {theta}, {n}): ", Chi(rho, theta, n))
  print("\n")

angle_colors = {
    -180: "brown",
    -135: "red",
    -90: "orange",
    -45: "yellow",
    0: "green",
    45: "blue",
    90: "purple",
    135: "pink",
}

radius_colors = {
    1: "brown",
    2: "red",
    3: "orange",
    4: "gold",
    5: "yellow",
}

def plot_convergence(rho, theta, max_iters):
  n = np.arange(0, max_iters+1, 1, dtype=int)
  Chi_vals = np.array([])
  for l in range(max_iters+1):
    Chi_vals = np.append(Chi_vals, Chi(rho, theta, l))
  if Chi_vals[-1] < 0.0:
    print(f"Warning: $\\chi$({rho},{theta}) = {Chi_vals[-1]} < 0 after {l} iterations")
  # else:
    # print(f"$\\chi$({rho},{theta}) converged to f{Chi_vals[-1]} after {l} iterations")
  plt.plot(n, Chi_vals, label=f"$\\chi$({rho},{theta})", color=radius_colors[rho])

epsilon_colors = {
    # 0.00001: "pink",
    # 0.0001: "black",
    0.001: "brown",
    0.01: "red",
    0.1: "orange",
    1: "gold",
    10: "yellow",
    100: "green",
    # 1000: "blue"
}

def plot_convergence_front_back(max_iters, front):
  if front:
    Chi_fnc = Chi_front
  else:
    Chi_fnc = Chi_back
  n = np.arange(0, max_iters+1, 1, dtype=int)
  Chi_vals = np.array([])
  for l in range(max_iters+1):
    Chi_vals = np.append(Chi_vals, Chi_fnc(l))
    if Chi_vals[-1] == np.nan:
      print(f"Warning: $\\chi_{{F}}$ = {Chi_vals[-1]} after {l} iterations")
      continue
  if Chi_vals[-1] < 0.0:
    print(f"Warning: $\\chi_{{F}}$ = {Chi_vals[-1]} < 0 after {l} iterations")
  # else:
    # print(f"$\\chi$({rho},{theta}) converged to f{Chi_vals[-1]} after {l} iterations")
  label = "F" if front else "B"
  plt.plot(n, Chi_vals, label=f"$\\chi_{label}$ at $\\varepsilon={epsilon}$", color=epsilon_colors[epsilon])

def compare_convergences_front_back(iters):
  for eps_val, color in epsilon_colors.items():
    set_epsilon(eps_val)
    plot_convergence_front_back(iters, True)
    plot_convergence_front_back(iters, False)

  plt.gcf().set_size_inches(10, 10)
  plt.plot(np.arange(0, iters+1, 1), np.zeros(iters+1), color="green", linestyle="--")
  plt.legend()
  plt.show()

def compare_convergences(eps_val, rho_min, rho_max, theta_min, theta_max, iters):
  set_epsilon(eps_val)
  for theta in range(theta_min, theta_max+1, 45):
    for rho in range(rho_min, rho_max+1):
      if rho is not 4: continue
      if is_near_pole(rho, theta): continue
      plot_convergence(rho, theta, iters)

  # plt.legend()
  plt.gcf().set_size_inches(10, 10)
  plt.plot(np.arange(0, iters+1, 1), np.zeros(iters+1), color="green", linestyle="--")
  plt.legend()
  plt.show()

def plot_chi_heatmap (x_bounds, z_bounds, cell_size, ax, iters=25, chi_debug=False):
  x, z = np.meshgrid(np.arange(x_bounds[0], x_bounds[1], cell_size), np.arange(z_bounds[0], z_bounds[1], cell_size))
  # doing normal np.atan(x / z) produces incorrect plot due to not picking the quadrants correctly
  chi = Chi(np.sqrt(z ** 2 + x ** 2), np.atan2(x, z), iters, chi_debug)
  img = ax.imshow(chi, extent=[x_bounds[0],x_bounds[1],z_bounds[0],z_bounds[1]], cmap="YlOrBr", origin='lower')
  ax.set_xlabel("x", fontsize="x-large")
  ax.set_ylabel("z", fontsize="x-large")
  ax.set_xticks([x_bounds[0], 0, x_bounds[1]])
  ax.set_yticks([z_bounds[0], 0, z_bounds[1]])
  ax.tick_params(labelsize="x-large")
  ax.set_title("$\\chi(\\lambda,\\theta)$", pad=10)
  return img

# Important: only works for cell sizes with one sig fig
# Also a lot slower, only use this version if you really need it
def plot_chi_heatmap_debug (x_bounds, z_bounds, num_cells_per_side, ax, iters=25, chi_debug=False):
  x_vals, z_vals = np.meshgrid( np.arange(x_bounds[0], x_bounds[1], (x_bounds[1] - x_bounds[0]) / num_cells_per_side),
                                np.arange(z_bounds[0], z_bounds[1], (z_bounds[1] - z_bounds[0]) / num_cells_per_side) )
  chis = []

  for z in z_vals[:, 0]:
    row = np.array([])
    for x in x_vals[0]:
      rho = np.sqrt( z**2 + x**2 )
      theta = np.atan2(x, z)
      chi = Chi(rho, theta, iters,  chi_debug)
      if chi < 0.0:
        print(f"Warning: $\\chi({rho}, {theta}) = {chi} < 0 after {iters} iterations)")
        chi = 0.0
      row = np.append(row, chi)
    chis.append(row)
    print(f"All chi values at z={z} found")

  img = ax.imshow(np.asarray(chis), extent=[x_bounds[0],x_bounds[1],z_bounds[0],z_bounds[1]], cmap="YlOrBr", origin='lower')
  ax.set_xlabel("x", fontsize="x-large")
  ax.set_ylabel("z", fontsize="x-large")
  ax.set_xticks([x_bounds[0], 0, x_bounds[1]])
  ax.set_yticks([z_bounds[0], 0, z_bounds[1]])
  ax.tick_params(labelsize="x-large")
  ax.set_title(f"$\\beta={beta}$, $\\varepsilon={epsilon}$", pad=10)
  return img

GREEK_LETTERS = {
    "alpha":   ("α", "Α"),
    "beta":    ("β", "Β"),
    "gamma":   ("γ", "Γ"),
    "delta":   ("δ", "Δ"),
    "epsilon": ("ε", "Ε"),
    "zeta":    ("ζ", "Ζ"),
    "eta":     ("η", "Η"),
    "theta":   ("θ", "Θ"),
    "iota":    ("ι", "Ι"),
    "kappa":   ("κ", "Κ"),
    "lambda":  ("λ", "Λ"),
    "mu":      ("μ", "Μ"),
    "nu":      ("ν", "Ν"),
    "xi":      ("ξ", "Ξ"),
    "omicron": ("ο", "Ο"),
    "pi":      ("π", "Π"),
    "rho":     ("ρ", "Ρ"),
    "sigma":   ("σ", "Σ"),
    "tau":     ("τ", "Τ"),
    "upsilon": ("υ", "Υ"),
    "phi":     ("φ", "Φ"),
    "chi":     ("χ", "Χ"),
    "psi":     ("ψ", "Ψ"),
    "omega":   ("ω", "Ω"),
}


def greek(s: str) -> str:
    """Convert a romanized Greek letter name to its Unicode symbol.

    Capitalization rules:
        - ALL CAPS  (e.g. "ALPHA") → uppercase Greek letter (Α)
        - Title case (e.g. "Alpha") → uppercase Greek letter (Α)
        - Anything else (e.g. "alpha") → lowercase Greek letter (α)

    Returns None if the string is not a recognized Greek letter name.
    """
    key = s.strip().lower()
    if key not in GREEK_LETTERS:
        return key

    lower, upper = GREEK_LETTERS[key]
    if s.isupper() or (s[0].isupper() and s[1:].islower()):
        return upper
    return lower

def plot_metric_heatmap (metric_name="output", metric_fnc=output, beta_max=5, eps_max=5, num_cells_per_side=25, ax=None, show_max=False, **kwargs):
  beta_vals, eps_vals = np.meshgrid(np.arange(0, beta_max, beta_max / num_cells_per_side), np.arange(0, eps_max, eps_max / num_cells_per_side))
  vals = []
  max_val = 0
  max_beta = 0
  max_eps = 0
  for eps_val in eps_vals[:, 0]:
    row = np.array([])
    for beta_val in beta_vals[0]:
      set_epsilon(eps_val)
      set_beta(beta_val)
      val = metric_fnc(**kwargs)
      # print(val)
      if val > max_val:
        max_beta = beta_val
        max_eps = eps_val
        max_val = val
      row = np.append(row, val)
    vals.append(row)


  print(f"Max {metric_name} = ({max_val}), reached at epsilon = {max_eps}, beta = {max_beta}")
  img = ax.imshow(np.asarray(vals), extent=[0, beta_max, 0, eps_max], cmap="YlOrBr", origin='lower')
  if show_max:
    ax.plot(max_beta, max_eps, 'x')
  ax.set_xlabel("$\\beta$", fontsize="x-large")
  # label = "$\\sqrt{{\\varepsilon}}$" if sqrt_eps else "$\\varepsilon$"
  ax.set_ylabel("$\\varepsilon$", fontsize="x-large")
  ax.set_xticks([0, beta_max])
  ax.set_yticks([0, eps_max])
  ax.tick_params(labelsize="x-large")
  ax.set_title(metric_name, pad=10)
  ax.set_aspect(max(beta_max, eps_max) / min(beta_max, eps_max))
  return img

def max_metric_val(metric_fnc=output, beta_max=5, eps_max=5, num_cells_per_side=25, **kwargs):
  beta_vals, eps_vals = np.meshgrid(np.arange(0, beta_max, beta_max / num_cells_per_side), np.arange(0, eps_max, eps_max / num_cells_per_side))
  vals = []
  max_val = 0
  max_beta = 0
  max_eps = 0
  for eps_val in eps_vals[:, 0]:
    row = np.array([])
    print("boom")
    for beta_val in beta_vals[0]:
      set_epsilon(eps_val)
      set_beta(beta_val)
      val = metric_fnc(**kwargs)
      print(val)
      if val > max_val:
        max_beta = beta_val
        max_eps = eps_val
        max_val = val
      row = np.append(row, val)
    vals.append(row)

  print(f"Max value = ({max_val}), reached at epsilon = {max_eps}, beta = {max_beta}")
  return max_eps, max_beta, max_val

gammas = np.linspace(0, 1, 20)

B_colors = {
    0.0001: "pink",
    0.001: "black",
    0.01: "brown",
    0.1: "red",
    1.0: "orange",
    10.0: "gold",
    100.0: "yellow",
    1000.0: "green",
    10000.0: "blue",
    100000.0: "purple"
}

def plot_budget_curves(metric_name="output", metric_fnc=output, Bmin=0.01, Bmax=100, ax=None):
  B = Bmin
  while B <= Bmax:
    vals = np.array([])
    for gamma in gammas:
      set_beta(B*(1 - gamma))
      set_epsilon(B*gamma)
      vals = np.append(vals, metric_fnc())

    maximizer_index = np.argmax(vals)
    print(f"Max {metric_name} = ({vals[maximizer_index]}), reached at gamma = {gammas[maximizer_index]}")
    ax.plot(gammas, vals, color=B_colors[B], label=f"B={B}")
    B *= 10

  ax.set_xlabel("$\\gamma$", fontsize="x-large")
  ax.set_ylabel(metric_name, fontsize="x-large")
  ax.set_xticks([0, 1])
  ax.tick_params(labelsize="x-large")
  # ax.set_xlim(0.9, 1)
  # ax.set_title("Production Possibilities Frontier: $\\beta$ & $\\epsilon$", fontsize="xx-large", pad=10)
  ax.legend()

def plot_for_multiple_kappas(kappa_vals, plot_fnc, figsize=(14, 5), by_row=False, num_cols = None, **kwargs):
  if by_row:
    fig, axes = plt.subplots(len(kappa_vals), num_cols, figsize=figsize, sharey='row')
  else:
    fig, axes = plt.subplots(1, len(kappa_vals), figsize=figsize)
  for i in range(len(kappa_vals)):
    set_kappa(kappa_vals[i])
    print(kappa)
    ax = axes if len(kappa_vals) == 1 else axes[i]
    print(ax)
    img = plot_fnc(ax=ax, **kwargs)
    ax.set_title(f"$\\kappa={kappa}$")
    if plot_fnc == plot_metric_heatmap: fig.colorbar(img, ax=ax, fraction=0.1)

def max_val_for_multiple_kappas(kappa_min, kappa_max, metric_fnc=bound_SNR, **kwargs):
  kappa_vals = np.logspace(kappa_min, kappa_max, 40)

  data = []
  max_eps_vals = []
  max_beta_vals = []
  for val in kappa_vals:
    set_kappa(val)
    print(f"Kappa = {val}")
    max_eps, max_beta, max_val= max_metric_val(metric_fnc, num_cells_per_side=10, **kwargs)
    max_eps_vals.append(max_eps)
    max_beta_vals.append(max_beta)
    data.append(max_val)

  plt.rcParams.update({'font.size': 22})
  sc = plt.scatter(max_beta_vals, max_eps_vals, c=kappa_vals, cmap="YlOrBr", norm="log")
  plt.xlabel("$\\beta$")
  plt.ylabel("$\\varepsilon$")
  plt.gcf().colorbar(sc)

# max_val_for_multiple_kappas(-3, 1)

def plot_output_heatmap (vs_beta, param_bounds, kappa_bounds, num_cells_per_side=25, ax=None, iters=25):
  param_vals, kappa_vals = np.meshgrid(
      np.arange(param_bounds[0], param_bounds[1] + np.abs(param_bounds[1] - param_bounds[0]) / num_cells_per_side, np.abs(param_bounds[1] - param_bounds[0]) / num_cells_per_side),
      np.arange(kappa_bounds[0], kappa_bounds[1] + np.abs(kappa_bounds[1] - kappa_bounds[0]) / num_cells_per_side, np.abs(kappa_bounds[1] - kappa_bounds[0]) / num_cells_per_side)
  )
  print(param_vals[0])
  print(kappa_vals[:, 0])
  if vs_beta:
    set_epsilon(0)
  else:
    set_beta(0)

  output_vals = []
  for kappa_val in kappa_vals[:, 0]:
    row = np.array([])
    for param_val in param_vals[0]:
      set_kappa(10 ** kappa_val)
      if vs_beta:
        set_beta(10 ** param_val)
      else:
        set_epsilon(10 ** param_val)
      row = np.append(row, output(iters))
    # print(row)
    output_vals.append(row)
    # print(output_vals)

  Z = np.asarray(output_vals)
  cf = ax.contourf(param_vals, kappa_vals, Z, levels=np.linspace(Z.min(), Z.max(), 8), cmap="YlOrRd")
  label = "beta" if vs_beta else "varepsilon"
  ax.set_xlabel(f"$\\log_{{10}}\\{label}$", fontsize="x-large")
  ax.set_ylabel("$\\log_{10}\\kappa$", fontsize="x-large")
  ax.set_xticks([param_bounds[0], 0, param_bounds[1]])
  ax.set_yticks([kappa_bounds[0], -1, kappa_bounds[1]])
  ax.tick_params(labelsize="x-large")
  ax.set_title("output", pad=10)
  return cf

from matplotlib.patches import ConnectionPatch

def plot_vs_isolated_params(metric_name="output", metric_fnc=output, enabled_params=(True, True), eps_max=100, beta_max=100, eps_min=0, beta_min=0, log_scale=False, width_factor=1, height_limit=None, line_offset=-0.15, axes=None, **kwargs):
  # fig, (ax1, ax2) = plt.subplots(1, 2)
  fig = plt.gcf()
  if axes == None:
    ax1 = plt.gca()
    ax2 = None
  elif len(axes) == 2:
    ax1 = axes[0]
    ax2 = axes[1]
  else:
    ax1 = axes[0]
    ax2 = None

  if enabled_params[0]:
    set_alpha(1)
    set_beta(0)

    if log_scale:
      eps_vals = np.array([])
      eps = eps_min
      while eps < eps_max:
        # print(f"Eps is now: {eps}")
        arr = np.linspace(eps, eps * 10, int(100 // eps))
        # print(arr)
        eps_vals = np.append(eps_vals, arr)
        eps *= 10
    else:
      eps_vals = np.linspace(eps_min, eps_max, 100)

    metric_vals = np.array([])
    max_val = 0.0
    max_eps_val = 0.0
    for eps_val in eps_vals:
      set_epsilon(eps_val)
      # print(f"Value appended at epsilon = {epsilon}")
      val = metric_fnc(**kwargs)
      if val > max_val:
        # print(f"new max val: {max_val}")
        max_val = val
        max_eps_val = epsilon
      metric_vals = np.append(metric_vals, val)
    print(f"Max {metric_name} = {max_val}, occurring at epsilon = {eps_vals[np.where(metric_vals == max_val)[0][0]]}")

    if log_scale:
      ax1.semilogx(eps_vals, metric_vals)
      ax1.set_xticks([0.01, 1, eps_max])
    else:
      ax1.plot(eps_vals, metric_vals)
      ax1.set_xticks([0, eps_max])
    ax1.set_xlabel("$\\epsilon$", fontsize="x-large")
    ax1.set_ylabel(metric_name, fontsize="x-large")
    # ax1.set_xticks([0.0, eps_max])
    ax1.set_yticks([0, np.round(max(metric_vals), 1)]) if height_limit == None else ax1.set_yticks([0, np.round(max(metric_vals), 1), height_limit])
    ax1.tick_params(labelsize="x-large")
    ax1.set_title(f"{metric_name} vs. $\\varepsilon$, $\\beta=0$", pad=10)
    # ax1.set_aspect(1.0/ax1.get_data_ratio(), adjustable='box')

  if enabled_params[1] and ax2 != None:
    set_alpha(1)
    set_epsilon(0)

    if log_scale:
      beta_vals = np.array([])
      beta = beta_min
      while beta < beta_max:
        beta_vals = np.append(beta_vals, np.linspace(beta, beta * 10, 10))
        beta *= 10
    else:
      beta_vals = np.linspace(beta_min, beta_max, 20)

    max_val = 0.0
    metric_vals = np.array([])
    for beta_val in beta_vals:
      set_beta(beta_val)
      # print(f"Value appended at epsilon = {epsilon}")
      val = metric_fnc(**kwargs)
      if val > max_val:
        max_val = val
      metric_vals = np.append(metric_vals, val)
    print(f"Max {metric_name} = {max_val}, occurring at beta = {np.where(metric_vals == max_val)}")

    if log_scale:
      ax2.semilogx(beta_vals, metric_vals)
      ax2.set_xticks([0.01, 1, beta_max])
    else:
      ax2.plot(beta_vals, metric_vals)
      ax2.set_xticks([0, beta_max])
    ax2.set_xlabel("$\\beta$", fontsize="x-large")
    ax2.tick_params(labelsize="x-large")

    # ax2.annotate(
    #   f"$\\kappa={kappa}$",
    #   xy=(1.02, 0.5),               # just outside the right edge, vertically centered
    #   xycoords="axes fraction",
    #   rotation=-90,                  # 90 degrees clockwise
    #   va="center",
    #   ha="left",
    #   fontsize="x-large",
    #   annotation_clip=False          # allows drawing outside the axes bounds
    # )
    ax2.set_title(f"{metric_name} vs. $\\beta$, $\\varepsilon=0$", pad=10)
    # ax2.set_ylim(0.0, ax1_max)
    # ax2.set_aspect(1.0/ax1.get_data_ratio(), adjustable='box')
    ax2.set_yticks([0, np.round(max(metric_vals), 1)])

  plt.tight_layout()

  # y_min = min(ax1.get_ylim()[0], ax2.get_ylim()[0])
  if ax2 != None:
    y_max = max(ax1.get_ylim()[1], ax2.get_ylim()[1]) if height_limit == None else height_limit
    ax1.set_ylim(0, y_max)
    ax2.set_ylim(0, y_max)

    # Draw the canvas so positions are finalized
    fig.canvas.draw()

    # Get current positions
    pos1 = ax1.get_position()
    pos2 = ax2.get_position()

    padding = 0.15
    if pos1.height >= pos2.height:
        ax1.set_position([pos1.x0, pos1.y0, pos1.width * width_factor, pos1.height])
        ax2.set_position([pos1.x0 + pos1.width * width_factor + padding, pos1.y0, pos2.width * width_factor, pos1.height])
    else:
        ax1.set_position([pos1.x0, pos2.y0, pos1.width * width_factor, pos2.height])
        ax2.set_position([pos1.x0 + pos1.width * width_factor + padding, pos2.y0, pos2.width * width_factor, pos2.height])

    xyA = (1e-3, y_max + line_offset)
    xyB = (0.99*beta_max, y_max + line_offset)
    con = ConnectionPatch(xyA=xyA, xyB=xyB, coordsA="data", coordsB="data",
                          axesA=ax1, axesB=ax2, color="gray", linestyle=(0, (5, 5)))
    ax2.add_artist(con)
    fig.canvas.draw()

  # plt.show()
  return max_eps_val

if __name__ == "__main__":
  num_vals = 20
  kappa_vals = np.logspace(-3, 1, num_vals)
  interval = num_vals / 4
  for i in range(0, num_vals, interval):
    print(i, i+interval)
    print(kappa_vals[i], kappa_vals[i+interval])
    plot_for_multiple_kappas(kappa_vals[i:i+interval], plot_metric_heatmap, beta_max=5, eps_max=5, metric_name="SNR$_B$", metric_fnc=bound_SNR, show_max=True, num_cells_per_side=10)
    plt.tight_layout()
    plt.show()
